### PR TITLE
Fix #1079 - bug in reset.sh

### LINKED ISSUE #1079: reset.sh breaking after passing to install.sh during check-minimum-requirements.sh line 3: file not found
### Version

nightly

### Steps to Reproduce

on an existing onpremise setup run ./reset.sh

after the call to install.sh check-minimum-requirements breaks at line 3: with the call to _min_requirements.sh not found.

seems while running in reset.sh and then calling install.sh the working directory changes to onpremise; however if running strictly in install.sh the working directory is onpremise/install

image

### Expected Result

reset.sh and then install.sh should flow correctly

### Actual Result

exits with check-minimum-requirements.sh: line 3: /root/onpremise/_min-requirements.sh: No such file or directory

image

### PR DESCRIPTION
**Pull request by chadwhitacre**
We need $0 to evaluate as install.sh in order for check-requirements to work.

### CODE REVIEW

File: reset.sh [hunk 1]
```diff
@@ -59,4 +59,4 @@ if [ -n "$version" ]; then
 fi
 
 # Install.
-exec ./install.sh
+./install.sh
```
Comment (armenzg) [inline reset.sh:62]: What was the original intent of using `exec`?

This piece of logic might be usable instead of `source "$(dirname $0)/_min-requirements.sh"`:
https://github.com/getsentry/sentry/blob/6776229fbde4ca8cd52884d369a1b498a43dc6b4/scripts/do.sh#L5-L10

Comment (chadwhitacre) [reply reset.sh:62]: I didn't have a strong reason to use `exec` originally. I did it that way because conceptually we are done with the one script so figured we'd hand off to the next, didn't think through the nuances.

I've started trying to whittle down a better repro in order to understand better what's going on and what the best solution is. That's turning out to take more time than I'd like, though. This `reset.sh` script is hacky and mostly for me. The real bug I want to focus on is #1133.

You okay to merge as-is?

**Review by armenzg — APPROVED** [review]
